In [1]:
from scipy.stats import multivariate_normal
import numpy as np

In [2]:
## set up multivariate norm used throughout tests
# 40% from mean = [2, 5], cov = [[1, .5], [.5, 100]]
# 60% from mean = [6, 9], cov = [[5, 3], [3, 40]]

mvn1 = multivariate_normal(mean = [2, 5], cov = [[1, .5], [.5, 100]])
mvn2 = multivariate_normal(mean = [6, 9], cov = [[5, 3], [3, 40]])
x11, x12 = 2.449356520423142, 22.228603905059355
pdfx1 = mvn1.pdf([x11, x12])
pdfx2 = mvn2.pdf([x11, x12])
pdfx1_weighted = pdfx1 * 0.4
pdfx2_weighted = pdfx2 * 0.6
print(pdfx1, pdfx2)
print(pdfx1_weighted, pdfx2_weighted)

## more data
x_vals = [[2.449356520423142, 22.228603905059355],
            [7.375567311048346, 7.658930529870852],
            [0.6206099136380241, -0.5206737056553434],
            [4.023896000998747, -1.1727896397005733],
            [7.794096850083458, 7.068473377153386]]

0.0033814120216 0.000148875770138
0.00135256480864 8.9325462083e-05


In [17]:
np.array(x_vals[2])

array([ 0.62060991, -0.52067371])

In [4]:
## eStepDatumTest
denom = pdfx1_weighted + pdfx2_weighted
print(pdfx1_weighted/denom, pdfx2_weighted/denom)

0.9380497504583296 0.06195024954167031


In [23]:
## logLikelihoodGMMTest
np.log(pdfx1_weighted + pdfx2_weighted)

-6.541800338213515

In [6]:
list(np.random.uniform(size=5))

[0.19765004055219848,
 0.36498221099062,
 0.1968909878188082,
 0.5009962966680894,
 0.7966995493558133]

In [3]:
test_array = np.array([1,2,5])
print(2 * test_array)

[ 2  4 10]


In [4]:
test_list = [0] * 3
print(test_list)
test_list[2] = 9
print(test_list)

[0, 0, 0]
[0, 0, 9]


In [5]:
a = np.array([1,2])
b = np.array([1,2])
a + b

array([2, 4])

In [6]:
wk_vals = [[0.98630233, 0.01369767],
                [0.93771556, 0.06228444],
                [0.62419835, 0.37580165],
                [0.98378211, 0.01621789],
                [0.9500608, 0.0499392]]
wk_vals = list(map(np.array,wk_vals))
wk_vals = np.array(wk_vals)
print(type(wk_vals), type(wk_vals[0]))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [7]:
wk_vals

array([[ 0.98630233,  0.01369767],
       [ 0.93771556,  0.06228444],
       [ 0.62419835,  0.37580165],
       [ 0.98378211,  0.01621789],
       [ 0.9500608 ,  0.0499392 ]])

In [22]:
def generate_wk(n):
    l1 = list(np.random.uniform(size = n))
    l2 = [1 - x for x in l1]
    return [np.array([x1,x2]) for x1,x2 in zip(l1,l2)]


def mean_calc(x_vals, wklist, nklist, kposition=0):
    #look up vector class for sum_val?
    k = len(nklist)
    n = len(x_vals)
    sum_val = np.array([0] * k)
    for i in range(n):
        sum_val = np.add(sum_val, np.multiply(wklist[i][kposition], np.array(x_vals[i])))
        
    return sum_val/nklist[kposition]

In [28]:
# wk_weights_ref = generate_wk(5)
# wk_weights = wk_weights_ref

In [23]:
## weights m step
wk_weights = wk_vals
nk_weights = [1.4, 3.6]
print(mean_calc(x_vals, wk_weights, nk_weights))
print("*******")
print(mean_calc(x_vals, wk_weights, nk_weights,1))

[ 15.05919768  24.53052035]
between
[ 0.32795829  0.25550444]
